name: Deploy application
env:
  environment:  ${{ github.ref_name == 'main' && 'development' || github.event.pull_request.base.ref }}
  MONGO_CONNECTION_STRING: "dummy-url"

on:
    workflow_dispatch:
    pull_request:
      branches: 
        - development

jobs:
    plan:
        name: 'Review, Prepare and Deploy'
        runs-on: 'self-hosted'
        environment: ${{ github.ref_name == 'main' && 'development' || github.event.pull_request.base.ref }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0         

            - name: Echo environment
              run: echo "Using environment [ ${environment} ]"
              shell: bash

            - name: 'Clean environment'
              run: rm -rf /tmp/gitleaks*
              shell: bash              

            - name: 'Looking for GIT Leaks'
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 'NPM deps installation'
              run: npm install
              shell: bash
              
            - name: 'Run ESLint'
              run: npm run lint  >> $GITHUB_STEP_SUMMARY
              shell: bash

            - name: 'Run tests'
              run: npm run test && cat ./test/results.md >> $GITHUB_STEP_SUMMARY
              shell: bash

            - name: 'Build application'
              run: npm run build
              shell: bash              

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}              

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: maleficarum/eversports:${{ github.sha }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: maleficarum/eversports:latest                

            - name: Docker Scout
              uses: docker/scout-action@v1.17.1
              with:
                  command: quickview,cves,recommendations
                  image: maleficarum/eversports:${{ github.sha }}
                  #dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
                  #dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}                