name: Deploy application
env:
  environment:  ${{ github.ref_name == 'main' && 'development' || github.ref_name }}

on:
    workflow_dispatch:
    pull_request:
      branches: 
        - development

jobs:
    plan:
        name: 'Review, Prepare and Deploy'
        runs-on: 'self-hosted'
        environment: ${{ github.ref_name == 'main' && 'development' || github.ref_name }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0         

            - name: Echo environment
              run: echo "Using environment [ ${environment} ]"
              shell: bash

            - name: 'Looking for GIT Leaks'
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 'NPM deps installation'
              run: npm install
              shell: bash
              
            - name: 'Run ESLint'
              run: npm run lint
              shell: bash
